spring:
  #main:
    #web-application-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: 111
    url: jdbc:postgresql://localhost:5430/library


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8070

logging:
  file:
    name: library.log
    path: /
  level:
    #root: warn
    com.example.library.service.impl.PersonDetailsServiceImpl: info








